### ISSUE TITLE
Account completion not work

### ISSUE THREAD

**Issue by wrvsrx** [polarmutex/beancount-language-server#32]
Date completion works well, but account completion doesn't work.

Examples:
![image](https://user-images.githubusercontent.com/42770726/124417000-ced19880-dd8a-11eb-8eb8-bf1c505abf1e.png)

Here's my configuration:
![image](https://user-images.githubusercontent.com/42770726/124417029-de50e180-dd8a-11eb-8c03-0ee661c2f5c3.png)

**Comment by wrvsrx** [comment]
Should I config treesitter additionally?

**Comment by xxgj** [comment]
+1

**Comment by polarmutex** [comment]
Tree sitter should not effect completion. I will try to reproduce and see what is going on. Thanks for reporting

**Comment by polarmutex** [comment]
I think I found the problem, It should be fixed in the develop branch in the repo

After I test the updated build over the next few days then I will move to main and create a release

**Comment by xxgj** [comment]
> I think I found the problem, It should be fixed in the develop branch in the repo
> 
> After I test the updated build over the next few days then I will move to main and create a release

Really appreciate your work:)

**Comment by peterhoeg** [comment]
FWIW, the problem persists with v1.3.1. Regular accounts completion using `beancount-mode` in emacs works as expected but not when using this LS.

**Comment by polarmutex** [comment]
Do you have a minimal config for eMacs that I can try?

**Comment by peterhoeg** [comment]
I do.

1. create a temporary directory and go there
2. put this file there as `emacs.org`
3. open `emacs.org` in emacs
4. M-x `org-babel-tangle`
5. Close emacs
6. Then `bash run.sh`

Try going to the last line and put in `Exp` then hit tab. It will auto-complete the `Expenses` part but then no more. Without LSP, it works fine (you can remove the `add-hook` bit to not start LSP.

```org-mode
* runner
#+begin_src sh :tangle run.sh
#!/usr/bin/env bash

emacs --init-directory=. test.beancount
#+end_src

* early
#+begin_src elisp :tangle early-init.el
;;; early-init.el --- Minimal config
(setq package-enable-at-startup nil)
#+end_src

* init
#+begin_src elisp :tangle init.el
;;; init.el --- Minimal config

;; straight.el
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+end_src

* eglot

#+begin_src elisp :tangle init.el
(use-package eglot
  :defer t
  :config
  (add-to-list 'eglot-server-programs '(beancount-mode "beancount-language-server" "--stdio")))
#+end_src

* beancount

#+begin_src elisp :tangle init.el
(straight-use-package '(beancount-mode :type git :host github :repo "beancount/beancount-mode"))

(use-package beancount
  :mode ("\\.beancount\\'" . beancount-mode)
  :config
  (add-hook 'beancount-mode-hook #'eglot-ensure))
#+end_src

#+begin_src beancount :tangle test.beancount
2000-01-01 open Expenses:Foo
2000-01-01 open Expenses:Bar
2023-01-01 open Expenses:NotOpenForThisTnx
2028-01-01 open Expenses:NotOpenYet

2001-01-01 * "Foo" "Expense"

#+end_src
```

**Comment by peterhoeg** [comment]
I did with 29.0.90 which has eglot (lsp support) built-in.

**Comment by polarmutex** [comment]
I will preface this with this, I am not a emacs user.

So I am running with the simple config and hit "Tab" and see "Expenses" fill in as you said. But If I hit "Tab" again I see a pop up with possible completions that seem what you  want. 

Could this be a configuration of eglot issue? I will play with it more and see If I see anything

**Comment by peterhoeg** [comment]
It could be eglot. I'll have to dig around a bit. Thanks for looking into
this and for the language server!

**Comment by aclindsa** [comment]
I appear to be seeing this same (or at least a similar) problem using neovim today.

Here's an example log from the language server:

```
2023-07-12T11:10:01.137321Z DEBUG lsp_server::msg: < {"method":"textDocument\/completion","id":6,"jsonrpc":"2.0","params":{"position":{"line":95910,"character":28},"textDocument":{"uri":"file:\/\/\/path\/to\/my\/ledger.beancount"}}}
2023-07-12T11:10:01.137727Z  INFO beancount_language_server::server: handling event Lsp(Request(Request { id: RequestId(I32(6)), method: "textDocument/completion", params: Object {"position": Object {"character": Number(28), "line": Number(95910)}, "textDocument": Object {"uri": String("file:///path/to/my/ledger.beancount")}} }))
2023-07-12T11:10:01.138736Z DEBUG beancount_language_server::providers::completion: providers::completion
2023-07-12T11:10:01.138832Z DEBUG beancount_language_server::providers::completion: providers::completion - line 95910
2023-07-12T11:10:01.138850Z DEBUG beancount_language_server::providers::completion: providers::completion - char 28
2023-07-12T11:10:01.138866Z DEBUG beancount_language_server::providers::completion: providers::completion - start (95910, 27)
2023-07-12T11:10:01.138884Z DEBUG beancount_language_server::providers::completion: providers::completion - end (95910, 28)
2023-07-12T11:10:01.138926Z DEBUG beancount_language_server::providers::completion: providers::completion - is_char_triggered None
2023-07-12T11:10:01.138956Z DEBUG beancount_language_server::providers::completion: providers::completion - node Some({Node account (95910, 2) - (95910, 28)})
2023-07-12T11:10:01.139022Z DEBUG beancount_language_server::providers::completion: providers::completion - text Expenses:Entertainment:Mus
2023-07-12T11:10:01.139075Z DEBUG beancount_language_server::providers::completion: providers::completion - parent node Some({Node posting (95910, 0) - (95911, 0)})
2023-07-12T11:10:01.139104Z DEBUG beancount_language_server::providers::completion: providers::completion - parent node Some({Node posting_or_kv_list (95910, 0) - (95913, 0)})
2023-07-12T11:10:01.139149Z DEBUG beancount_language_server::providers::completion: providers::completion - prev sibling node None
2023-07-12T11:10:01.139199Z DEBUG beancount_language_server::providers::completion: providers::completion - prev named node None
2023-07-12T11:10:01.139243Z DEBUG beancount_language_server::providers::completion: providers::completion - handle node
2023-07-12T11:10:01.139793Z  INFO beancount_language_server::server: handling event Task(Response(Response { id: RequestId(I32(6)), result: Some(Null), error: None }))
2023-07-12T11:10:01.139839Z  INFO beancount_language_server::server: handled req#6 in 1.968957ms
2023-07-12T11:10:01.139890Z DEBUG lsp_server::msg: > {"jsonrpc":"2.0","id":6,"result":null}
```

The relevant transaction in my beancount file looks like:

```
2023-07-11 * "Fandango" "Fandango"
  Expenses:Entertainment:Mus
  Liabilities:Credit-Card  -30.64 USD
```

You'll see that I'm trying to auto-complete the "Expenses:Entertainment:Mus" account, which should complete to "Expenses:Entertainment:Music-Movies", which is a valid and existing account in my beancount file. But the server doesn't seem to return any completions for it.

**Comment by valpackett** [comment]
Using Helix and the latest version currently available on crates.io, account completions only appear for me when I *backspace and type a letter that would result in fuzzy completions i.e. exists in some account with that prefix EXCEPT FOR the next letter* :exploding_head:

![wtf rec](https://github.com/polarmutex/beancount-language-server/assets/208340/9f821291-f160-4218-9ce1-9c89a5b4b84a)

**Comment by polarmutex** [comment]
have not seen this with Neovim, I can play with Helix when I get a chance and see what is happening

**Comment by LumenYoung** [comment]
I can't get completion as well but all other work fine. Would be nice if we can sort this out

**Comment by Bergschrat1** [comment]
Hey,
First of all, thanks for the great work on this project!
I'm using Helix and for me it's also the account completion that isn't working.
What I have noticed is that the logs look different if it's the first posting or if it's the second:
### First posting
```beancount
2023-10-01 open Assets:Test USD
2023-10-01 open Expenses:Test USD
2023-10-01 txn  "Test Co" "Foo Bar"
    Assets:T
```
```
2024-10-27T19:40:14.942571Z DEBUG beancount_language_server::handlers::text_document: handlers::did_change
2024-10-27T19:40:14.942573Z DEBUG beancount_language_server::handlers::text_document: handlers::did_change - requesting file:///path/to/my/file/test.beancount
2024-10-27T19:40:14.942576Z DEBUG beancount_language_server::handlers::text_document: handlers::did_change - convert edits
2024-10-27T19:40:14.942584Z DEBUG beancount_language_server::handlers::text_document: handlers::did_change - apply edits - document
2024-10-27T19:40:14.942589Z DEBUG beancount_language_server::handlers::text_document: handlers::did_change - apply edits - tree
2024-10-27T19:40:14.942656Z DEBUG beancount_language_server::handlers::text_document: handlers::did_change - save tree
2024-10-27T19:40:14.942660Z DEBUG beancount_language_server::beancount_data: beancount_data:: get account nodes
2024-10-27T19:40:14.942662Z DEBUG beancount_language_server::beancount_data: beancount_data:: get account strings
2024-10-27T19:40:14.942664Z DEBUG beancount_language_server::beancount_data: beancount_data:: update accounts
2024-10-27T19:40:14.942674Z DEBUG beancount_language_server::beancount_data: beancount_data:: get narration nodes
2024-10-27T19:40:14.942676Z DEBUG beancount_language_server::beancount_data: beancount_data:: get account strings
2024-10-27T19:40:14.942682Z DEBUG beancount_language_server::beancount_data: beancount_data:: update narration
2024-10-27T19:40:14.942684Z DEBUG beancount_language_server::beancount_data: beancount_data:: update flagged entries
2024-10-27T19:40:14.942687Z DEBUG beancount_language_server::beancount_data: beancount_data:: get tags
2024-10-27T19:40:14.942817Z DEBUG beancount_language_server::beancount_data: beancount_data:: get tags
2024-10-27T19:40:14.942940Z DEBUG beancount_language_server::handlers::text_document: handlers::did_close - done

```
### Second (or any following) posting
```
2023-10-01 open Assets:Test USD
2023-10-01 open Expenses:Test USD
2023-10-01 txn  "Test Co" "Foo Bar"
    Assets:Test   -5 USD
    Expe 
```
```
2024-10-27T19:45:49.461588Z DEBUG beancount_language_server::providers::completion: providers::completion
2024-10-27T19:45:49.461612Z DEBUG beancount_language_server::providers::completion: providers::completion - line 4 char 8
2024-10-27T19:45:49.461624Z DEBUG beancount_language_server::providers::completion: providers::completion - prev sibling node None
2024-10-27T19:45:49.461630Z DEBUG beancount_language_server::providers::completion: providers::completion - prev named sibling node None
2024-10-27T19:45:49.461634Z DEBUG beancount_language_server::providers::completion: providers::completion - parent node Some({Node ERROR (4, 0) - (4, 8)})
2024-10-27T19:45:49.461640Z DEBUG beancount_language_server::providers::completion: providers::completion - handle node Some({Node ERROR (4, 4) - (4, 8)})
2024-10-27T19:45:49.461650Z DEBUG beancount_language_server::providers::completion: providers::completion - text Expe
2024-10-27T19:45:49.461654Z DEBUG beancount_language_server::providers::completion: providers::completion - handle node
2024-10-27T19:45:49.461750Z  INFO beancount_language_server::server: handling event Task(Response(Response { id: RequestId(I32(17)), result: Some(Null), error: None }))
2024-10-27T19:45:49.461853Z  INFO beancount_language_server::server: handled req#17 in 357.173µs
2024-10-27T19:45:49.461927Z DEBUG lsp_server::msg: > {"jsonrpc":"2.0","id":17,"result":null}    
```

**Comment by polarmutex** [comment]
I have noticed some oddities with completions on my setup with Neovim.

its on my list to look at soon

**Comment by sohanglal** [comment]
Completions haven't been working at all on my end. I have been using this project : [GitHub - crispgm/cmp-beancount: nvim-cmp source for beancount accounts](https://github.com/crispgm/cmp-beancount). It is working really well

**Comment by polarmutex** [comment]
i overhauled the completion engine, should be working much better once 1.4 is released. closing for now and can reopen if still having issues on the new version

**Comment by TheKevJames** [comment]
Just wanted to confirm that v1.4.1 fixed completions for me, appreciate the work on this! One bug I'm noticing, though, is duplicated quotes when the completion is for a transaction description. Example:

<img width="655" height="50" alt="Image" src="https://github.com/user-attachments/assets/14f8d6bc-fbf5-4b79-857c-3ffb4eeee37b" />

(press ctrl-y to accept the highlighted completion)

<img width="178" height="28" alt="Image" src="https://github.com/user-attachments/assets/b0a953ce-610c-49cd-8e86-895f4703da88" />
